public class tipos_de_dados {
    public static void main(String[] args) {
        
        int idade; 
        double salario; 
        String nomes;
        char generos;

        idade = 30; 
        salario = 4.50; 
        nomes = "Julio"; 
        generos = 'M'; 

        System.out.println("Idade = " + idade );
        System.out.println("Salario = " String.format("%.2f"+ salario);
        System.out.println("Genero = " + generos);
        System.out.println("Nome = " + nomes); 

    }
}